### ISSUE TITLE
Does not load queries when published in Native Aot mode on linux-x64 

### ISSUE THREAD

**Issue by amiralichesser3** [ose-net/yesql.net#112]
After publishing my app in Nativ Aot Mode (/p:UseAppHost=true /p:PublishAot=true), the yesql folder and the queries are copied in my linux docker container, but they don't seem to be loading correctly and I get YeSql.Net.TagNotFoundException : The given tag '{MY_TAG}' was not present in the collection.

**Comment by DevD4v3** [comment]
Hello @amiralichesser3,

I have used this [sample](https://github.com/ose-net/yesql.net/tree/b7ffdcddd0c185686cbe87d8a0c70dc0b5f1ad47/samples/Example.ConsoleApp) and compiled it in AOT mode on both windows-x64 and alpine-x64 (without docker) and it seems to work fine.

I then tested it with Docker using the above sample and it also works. My Dockerfile is this:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app
RUN apt update
RUN apt install -y clang zlib1g-dev

COPY samples/Example.ConsoleApp/*.csproj .
RUN dotnet restore "Example.ConsoleApp.csproj"
COPY . .

RUN dotnet publish "samples/Example.ConsoleApp/Example.ConsoleApp.csproj" -c Release --self-contained false -o /app/publish /p:AOT=true /p:UseAppHost=true

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["./Example.ConsoleApp"]
```
### Output:
![image](https://github.com/ose-net/yesql.net/assets/43916038/4e066bca-249f-4a40-8cb8-1ee746231333)

To reproduce your problem I would need more information. What type of application is it, webapi? How is your Dockerfile written?

Also note that the **tags** are **case sensitive** (GetProducts != getProducts).

**Comment by amiralichesser3** [comment]
The dockerfile:
```Dockerfile
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled-extra AS base
USER $APP_UID
WORKDIR /app
EXPOSE 5276
FROM mcr.microsoft.com/dotnet/nightly/sdk:8.0-jammy-aot AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["HxcCommon/HxcCommon.csproj", "HxcCommon/"]
RUN dotnet restore -r linux-x64 "HxcCommon/HxcCommon.csproj"

COPY ["HxcApi/HxcApi/HxcApi.csproj", "HxcApi/HxcApi/"]
RUN dotnet restore -r linux-x64 "HxcApi/HxcApi/HxcApi.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build -r linux-x64 "HxcCommon/HxcCommon.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN dotnet build -r linux-x64 "HxcApi/HxcApi/HxcApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "HxcApi/HxcApi/HxcApi.csproj"  --no-restore -r linux-x64 -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=true /p:PublishAot=true

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./HxcApi"]
```
My guess is that it is a permission issue on accessing the .sql files on mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled-extra

**Comment by DevD4v3** [comment]
Good morning @amiralichesser3,

Your project is open source right? https://github.com/amiralichesser3/HxcApi/tree/develop

Could you upload the changes using yesql.net to reproduce the problem? Please.
It can be in a different branch if you like.

**Comment by amiralichesser3** [comment]
sure, you can find it on this branch: https://github.com/amiralichesser3/HxcApi/tree/feature/15_cqrs

**Comment by DevD4v3** [comment]
Hi @amiralichesser3,

The problem is that the [Directory.GetFiles](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=net-8.0#system-io-directory-getfiles(system-string-system-string-system-io-searchoption)) method is case sensitive in Linux. You have a file called "QueryTodos.Sql", as the extension is `.Sql`, this line will return an empty array on a Linux distro:
https://github.com/ose-net/yesql.net/blob/b7ffdcddd0c185686cbe87d8a0c70dc0b5f1ad47/src/Loader/YeSqlLoader.HelperMethods.cs#L106

There is an open issue here: https://github.com/dotnet/core/issues/4596
The comment from svick should solve this problem, however the EnumerationOptions type is only available for .NET Standard 2.1 and I want this library to be compatible with .NET Framework as well.

You just have to change the extension to `.sql` and everything should work (I already tested it).

**Comment by amiralichesser3** [comment]
Thanks mate, really appreciate it!
